apiVersion: v1
kind: ConfigMap
metadata:
  name: config-bg-blue
data:
  BG_COLOR: blue
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-bg-green
  data:
  BG_COLOR: green

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app-deployment
  labels:
    app: weather-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
      - name: weather-app-container
        image: nickgofman/weather:color
        ports:
        - containerPort: 9090
        envFrom:
        - configMapRef:
            name: config-bg-blue



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: soliter-deployment
  labels:
    app: soliter
spec:
  replicas: 4
  selector:
    matchLabels:
      app: soliter
  template:
    metadata:
      labels:
        app: soliter
    spec:
      containers:
      - name: soliter-container
        image: nickgofman/my-custom-solitaire:latest
        ports:
        - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weather-app-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: a484ec65fd5d848c39288cf4bb9e51d2-487660707.eu-north-1.elb.amazonaws.com
    http:
      paths:

      - backend:
          service:
            name: weather-app-service
            port:
              number: 80
        path: /
        pathType: Prefix


      - backend:
          service:
            name: weather-app-service
            port:
              number: 80
        path: /static/*
        pathType: Prefix


---

apiVersion: v1
kind: Service
metadata:
  name: soliter-service
  labels:
    app: soliter
spec:
  type: ClusterIP
  selector:
    app: soliter
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
  labels:
    app: weather-app
spec:
  type: ClusterIP
  selector:
    app: weather-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090
