version: 2.1

orbs:
  discord: antonioned/discord@0.1.0
  bridgecrew: bridgecrew/bridgecrew@1.0.5
  aws-eks: circleci/aws-eks@1.0.0
  kubernetes: circleci/kubernetes@0.11.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - setup_remote_docker:
          version: docker23  
          docker_layer_caching: true

      - run:
          name: Run Tests
          command: docker-compose build

      - run:
          name: Run Tests
          command: docker-compose up -d


      - run:
          name: Login to GitLab Container Registry
          command: |
            docker login registry.gitlab.com -u $GIT_LAB_USER -p $GIT_LAB_PASS

      - run:
          name: Tag Image
          command: |
            docker tag project_flask_app registry.gitlab.com/team1414207/cicleci:1.0.$CIRCLE_BUILD_NUM


      - run:
          name: Push Docker Image to GitLab Container Registry
          command: |
            docker push registry.gitlab.com/team1414207/cicleci:1.0.$CIRCLE_BUILD_NUM

      - discord/status:
          fail_only: false
          failure_message: "**${CIRCLE_USERNAME}**'s build: **${CIRCLE_JOB}** failed."
          success_message: "**${CIRCLE_USERNAME}** deployed api to prod."
          webhook: "${URL_DISCORD}"

  terraform_checkov:
    executor: bridgecrew/default
    steps:
      - checkout
      - bridgecrew/scan:
          api-key-variable: BC_API_KEY
          directory: ./terraform
          output: json
          soft-fail: false

  deploy-to-aws:
    executor: aws-eks/python3
    steps:
      - checkout
      - run:
          name: Initialize Terraform
          command: |
            cd ./terraform
            terraform init
      - run:
          name: Apply Terraform Configuration
          command: |
            cd ./terraform
            terraform apply -auto-approve


workflows:
  my-workflow:
    jobs:
      - build
      - terraform_checkov:
          requires:
            - build
      - deploy-to-aws:
          requires:
            - build
            - terraform_checkov
