version: 2.1

orbs:
  discord: antonioned/discord@0.1.0

jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - setup_remote_docker:
          version: docker23  # Ensure a compatible Docker version
          docker_layer_caching: true

 #     - run:
 #         name: Build Docker image
 #         command: docker build -t weatherapp ./app/

#      - run:
#          name: Start Docker container
#          command: docker run -d -p 8000:9090 --name weatherapp_container weatherapp

#      - run:
#          name: Run Tests
#          command: python -m unittest discover -s ./app/tests
      - run:
          name: Run Tests
          command: docker-compose build

      - run:
          name: Run Tests
          command: docker-compose up -d


      - run:
          name: Login to GitLab Container Registry
          command: |
            docker login registry.gitlab.com -u $GIT_LAB_USER -p $GIT_LAB_PASS

      - run:
          name: Tag Image
          command: |
            docker tag project_flask_app registry.gitlab.com/team1414207/cicleci:1.0.$CIRCLE_JOB_NUM 


      - run:
          name: Push Docker Image to GitLab Container Registry
          command: |
            docker push registry.gitlab.com/team1414207/cicleci:1.0.$CIRCLE_JOB_NUM


      - discord/status:
          fail_only: false
          failure_message: "**${CIRCLE_USERNAME}**'s build: **${CIRCLE_JOB}** failed."
          success_message: "**${CIRCLE_USERNAME}** deployed api to prod."
          webhook: "${URL_DISCORD}"
